// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyShelter.Infrastructure;

#nullable disable

namespace MonkeyShelter.Infrastructure.Migrations
{
    [DbContext(typeof(MonkeyShelterDbContext))]
    [Migration("20250527155418_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Monkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Monkeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8e390cd-76b8-4b20-b397-e18a3175a161"),
                            ArrivalDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera1",
                            ShelterId = 1,
                            SpeciesId = 1,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("04999673-5408-43ac-9eab-8e0af9798190"),
                            ArrivalDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika1",
                            ShelterId = 1,
                            SpeciesId = 1,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("0111cc28-1ead-4973-9a2f-b8e89869489c"),
                            ArrivalDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza1",
                            ShelterId = 1,
                            SpeciesId = 1,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("846ef5ab-c3a7-4080-97bf-99f6d576388e"),
                            ArrivalDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova1",
                            ShelterId = 1,
                            SpeciesId = 1,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("ac89233f-efbf-4c05-8b69-6598a4388b63"),
                            ArrivalDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima1",
                            ShelterId = 1,
                            SpeciesId = 1,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("71c98498-776c-4562-b00d-cc57aff50095"),
                            ArrivalDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica1",
                            ShelterId = 1,
                            SpeciesId = 1,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("466d7f08-b362-4698-b818-16269200dd74"),
                            ArrivalDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera2",
                            ShelterId = 1,
                            SpeciesId = 2,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("43c6dcd8-b0fe-49e4-87d0-4d0eec6fb84b"),
                            ArrivalDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika2",
                            ShelterId = 1,
                            SpeciesId = 2,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("cd8ba658-2f1a-4076-bcc9-c367d06c8bb3"),
                            ArrivalDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza2",
                            ShelterId = 1,
                            SpeciesId = 2,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("cd7e8e0b-9f30-4f1e-a4c3-de2dd05bd793"),
                            ArrivalDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova2",
                            ShelterId = 1,
                            SpeciesId = 2,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("40c773a7-1d82-4dc5-bb4f-0b705a188c70"),
                            ArrivalDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima2",
                            ShelterId = 1,
                            SpeciesId = 2,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("438cc2ee-91d1-4f72-b4cf-b353c467e0d9"),
                            ArrivalDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica2",
                            ShelterId = 1,
                            SpeciesId = 2,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("627de6f7-604e-457b-b1d0-b57fa1d11083"),
                            ArrivalDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera3",
                            ShelterId = 1,
                            SpeciesId = 3,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("58867445-a5dd-4f67-94b9-f1fadd9ed279"),
                            ArrivalDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika3",
                            ShelterId = 1,
                            SpeciesId = 3,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("eeb9bc8b-1277-4ec9-8817-cb3c05f73f07"),
                            ArrivalDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza3",
                            ShelterId = 1,
                            SpeciesId = 3,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("03d71cb3-a68b-448e-9f00-6d2db66bcc1c"),
                            ArrivalDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova3",
                            ShelterId = 1,
                            SpeciesId = 3,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("7151343a-29ad-45d3-a4ab-9e09bc42973b"),
                            ArrivalDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima3",
                            ShelterId = 1,
                            SpeciesId = 3,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("c86df92d-efae-4870-b6b4-24f31f95a17f"),
                            ArrivalDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica3",
                            ShelterId = 1,
                            SpeciesId = 3,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("6a2fe30f-d0bf-4973-8cd3-de390e243b75"),
                            ArrivalDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera4",
                            ShelterId = 1,
                            SpeciesId = 4,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("e861c6d5-8692-4a03-aa6d-43f1ba5a2bd0"),
                            ArrivalDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika4",
                            ShelterId = 1,
                            SpeciesId = 4,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("c0839795-4123-4d40-b682-7a1874042698"),
                            ArrivalDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza4",
                            ShelterId = 1,
                            SpeciesId = 4,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("af6d2531-265d-4653-bf40-9a2e75cf92ef"),
                            ArrivalDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova4",
                            ShelterId = 1,
                            SpeciesId = 4,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("13165eaf-8d2d-4ab6-a8ee-551a18023cd0"),
                            ArrivalDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima4",
                            ShelterId = 1,
                            SpeciesId = 4,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("6c3fe9fe-6ac5-4133-a02f-43506ef86240"),
                            ArrivalDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica4",
                            ShelterId = 1,
                            SpeciesId = 4,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("48ddc4f3-1120-44e4-a090-61fb2ce96c14"),
                            ArrivalDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera5",
                            ShelterId = 1,
                            SpeciesId = 5,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("dcf37036-4689-466e-a869-07c2da3af52c"),
                            ArrivalDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika5",
                            ShelterId = 1,
                            SpeciesId = 5,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("fb07fc84-cde4-4c2e-80d0-8d7e153e916c"),
                            ArrivalDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza5",
                            ShelterId = 1,
                            SpeciesId = 5,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("99cceea0-1f8f-4c1d-a23f-3376007d44fc"),
                            ArrivalDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova5",
                            ShelterId = 1,
                            SpeciesId = 5,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("0dcbbdbd-e74b-46e8-ab32-0ccbfae47465"),
                            ArrivalDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima5",
                            ShelterId = 1,
                            SpeciesId = 5,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("9e512851-3e4d-4608-afcc-aab57cd28942"),
                            ArrivalDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica5",
                            ShelterId = 1,
                            SpeciesId = 5,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("725cc9a4-1fdb-4064-a72b-cd7e8e95eb7c"),
                            ArrivalDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera6",
                            ShelterId = 1,
                            SpeciesId = 6,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("bc803d57-9185-4710-93d9-f2981e6e4242"),
                            ArrivalDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika6",
                            ShelterId = 1,
                            SpeciesId = 6,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("21a42287-dcdb-4838-ae3e-d379a22fc004"),
                            ArrivalDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza6",
                            ShelterId = 1,
                            SpeciesId = 6,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("56067503-20ec-4a6b-9cac-f4c466a645c4"),
                            ArrivalDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova6",
                            ShelterId = 1,
                            SpeciesId = 6,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("6e267371-7cb3-4f63-afa1-c876e44691f5"),
                            ArrivalDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima6",
                            ShelterId = 1,
                            SpeciesId = 6,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("20a8648e-dc0c-4815-bd14-b89ce4e04c74"),
                            ArrivalDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica6",
                            ShelterId = 1,
                            SpeciesId = 6,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("a5b976ad-6c12-494c-8b98-aa91d378c62b"),
                            ArrivalDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera7",
                            ShelterId = 1,
                            SpeciesId = 7,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("4f301620-8e76-4d95-b92e-3e1addc8d706"),
                            ArrivalDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika7",
                            ShelterId = 1,
                            SpeciesId = 7,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("06ff6efb-45ef-4747-94d5-21eb5cfdb7a3"),
                            ArrivalDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza7",
                            ShelterId = 1,
                            SpeciesId = 7,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("0cd3df03-ab4a-427e-9751-9a38b5902a3f"),
                            ArrivalDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova7",
                            ShelterId = 1,
                            SpeciesId = 7,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("4b8a14c1-fd79-43ee-bb54-420344931cef"),
                            ArrivalDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima7",
                            ShelterId = 1,
                            SpeciesId = 7,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("3fab5e6f-df96-483f-9824-e8ccfea70f41"),
                            ArrivalDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica7",
                            ShelterId = 1,
                            SpeciesId = 7,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("24450d97-b650-47a9-b65c-41c69f7bc8bb"),
                            ArrivalDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera8",
                            ShelterId = 1,
                            SpeciesId = 8,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("a291a9b7-5312-4236-9ae1-9dfba00f7562"),
                            ArrivalDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika8",
                            ShelterId = 1,
                            SpeciesId = 8,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("6c861032-ef62-4ef9-84f8-9a11aeedc484"),
                            ArrivalDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza8",
                            ShelterId = 1,
                            SpeciesId = 8,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("0f153dc2-a163-4233-a845-dfa3a84487ab"),
                            ArrivalDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova8",
                            ShelterId = 1,
                            SpeciesId = 8,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("a8394419-f65a-467d-ae69-04df0f0e964f"),
                            ArrivalDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima8",
                            ShelterId = 1,
                            SpeciesId = 8,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("42029059-8fb7-49c2-8355-6da8f1b928d8"),
                            ArrivalDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica8",
                            ShelterId = 1,
                            SpeciesId = 8,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("b2f702b7-c13d-4510-b773-edb3701c4840"),
                            ArrivalDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera9",
                            ShelterId = 1,
                            SpeciesId = 9,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("b70ecbc9-9439-473d-b734-c524c1e64c65"),
                            ArrivalDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika9",
                            ShelterId = 1,
                            SpeciesId = 9,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("7ae7641d-050c-4d18-bd4b-754e5e29ff88"),
                            ArrivalDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza9",
                            ShelterId = 1,
                            SpeciesId = 9,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("4754f9a1-b49a-4b59-b8ed-c7ae893debaf"),
                            ArrivalDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova9",
                            ShelterId = 1,
                            SpeciesId = 9,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("92a656c0-4f51-463c-b8bf-e4d1f522a5f1"),
                            ArrivalDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima9",
                            ShelterId = 1,
                            SpeciesId = 9,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("70120d00-c1ff-4187-b549-eadaa924aa17"),
                            ArrivalDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica9",
                            ShelterId = 1,
                            SpeciesId = 9,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("f5fab2e8-c06d-42a6-92b2-bd07cedf1156"),
                            ArrivalDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera10",
                            ShelterId = 1,
                            SpeciesId = 10,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("a3a068f9-bc9f-49bf-a41d-2ad631557890"),
                            ArrivalDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika10",
                            ShelterId = 1,
                            SpeciesId = 10,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("c7515ad4-9435-4c04-8141-6b99d866e87c"),
                            ArrivalDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza10",
                            ShelterId = 1,
                            SpeciesId = 10,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("cf0a3ad4-901f-4f53-a130-0ba2841da7cb"),
                            ArrivalDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova10",
                            ShelterId = 1,
                            SpeciesId = 10,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("301b697d-480d-47f4-a5d9-56cf64db9e2b"),
                            ArrivalDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima10",
                            ShelterId = 1,
                            SpeciesId = 10,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("df3439af-d580-472c-9c62-a459c2abe610"),
                            ArrivalDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica10",
                            ShelterId = 1,
                            SpeciesId = 10,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("c54c6207-2f4d-402a-88cd-88b3343a421d"),
                            ArrivalDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera11",
                            ShelterId = 1,
                            SpeciesId = 11,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("af19443f-add8-4f27-abb2-4747429ab6b7"),
                            ArrivalDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika11",
                            ShelterId = 1,
                            SpeciesId = 11,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("5235fd66-7468-4f8b-98e4-08b54f3e868a"),
                            ArrivalDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza11",
                            ShelterId = 1,
                            SpeciesId = 11,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("49fab9d1-5f65-4717-a97f-977ed0d46cb9"),
                            ArrivalDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova11",
                            ShelterId = 1,
                            SpeciesId = 11,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("dc748ffd-9b59-4fb4-8140-ced416cafa2d"),
                            ArrivalDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima11",
                            ShelterId = 1,
                            SpeciesId = 11,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("f0e96d63-0ac5-4551-b13e-33bbad085d0f"),
                            ArrivalDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica11",
                            ShelterId = 1,
                            SpeciesId = 11,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("25c282b4-1fd3-496c-8915-f9e434e4041e"),
                            ArrivalDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera12",
                            ShelterId = 1,
                            SpeciesId = 12,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("702a8e87-0da2-4964-a57d-1d97986fdd97"),
                            ArrivalDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika12",
                            ShelterId = 1,
                            SpeciesId = 12,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("bb26cbc4-e9e3-412a-8963-bc39d9ae160c"),
                            ArrivalDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza12",
                            ShelterId = 1,
                            SpeciesId = 12,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("2a9833eb-cff7-4580-9ec2-2eea1caabd6f"),
                            ArrivalDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova12",
                            ShelterId = 1,
                            SpeciesId = 12,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("17d279cc-689f-4874-90ae-e2644b2c59ba"),
                            ArrivalDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima12",
                            ShelterId = 1,
                            SpeciesId = 12,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("4c8be266-ece0-4c03-a94b-822e4cd4b67c"),
                            ArrivalDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica12",
                            ShelterId = 1,
                            SpeciesId = 12,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("af51b546-cd94-4f46-9eca-d2770ac77a6f"),
                            ArrivalDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera13",
                            ShelterId = 1,
                            SpeciesId = 13,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("8b3b82ec-e195-4c72-9e2a-d586c93b2e78"),
                            ArrivalDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika13",
                            ShelterId = 1,
                            SpeciesId = 13,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("e0789f08-858d-42c9-9c23-aa4e97cde77d"),
                            ArrivalDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza13",
                            ShelterId = 1,
                            SpeciesId = 13,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("ca262390-c139-4a7b-90d2-e70d58386ff6"),
                            ArrivalDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova13",
                            ShelterId = 1,
                            SpeciesId = 13,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("d5570c47-e2ad-4460-8394-cddd851604d7"),
                            ArrivalDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima13",
                            ShelterId = 1,
                            SpeciesId = 13,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("8deb0c93-57d8-4150-9b03-dd0aba3a7001"),
                            ArrivalDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica13",
                            ShelterId = 1,
                            SpeciesId = 13,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("bba9c97b-0707-4b3b-8b47-8532be78ca99"),
                            ArrivalDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera14",
                            ShelterId = 1,
                            SpeciesId = 14,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("3fb8b5b6-8d22-4a3c-99bf-e9923bb81036"),
                            ArrivalDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika14",
                            ShelterId = 1,
                            SpeciesId = 14,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("8be3d780-41e1-4d78-a2d4-411908d8a396"),
                            ArrivalDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza14",
                            ShelterId = 1,
                            SpeciesId = 14,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("2040ad2c-69b3-4129-8aae-628a81c34015"),
                            ArrivalDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova14",
                            ShelterId = 1,
                            SpeciesId = 14,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("6977c50f-63ca-4c8b-a9e4-c20edce86caa"),
                            ArrivalDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima14",
                            ShelterId = 1,
                            SpeciesId = 14,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("9187e29f-934a-422f-bbc9-55685dcfb1a6"),
                            ArrivalDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica14",
                            ShelterId = 1,
                            SpeciesId = 14,
                            Weight = 77.0
                        },
                        new
                        {
                            Id = new Guid("cfada7f8-326b-485f-bce1-9eb9dff30544"),
                            ArrivalDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pera15",
                            ShelterId = 1,
                            SpeciesId = 15,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = new Guid("78dcfb89-4eda-4949-9b87-93bcac428348"),
                            ArrivalDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mika15",
                            ShelterId = 1,
                            SpeciesId = 15,
                            Weight = 33.0
                        },
                        new
                        {
                            Id = new Guid("dcde0d5f-47c8-454b-aafd-8dfb9a0052ab"),
                            ArrivalDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laza15",
                            ShelterId = 1,
                            SpeciesId = 15,
                            Weight = 44.0
                        },
                        new
                        {
                            Id = new Guid("d6d349be-1e52-463a-9ef5-3802f38e61fa"),
                            ArrivalDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jova15",
                            ShelterId = 1,
                            SpeciesId = 15,
                            Weight = 55.0
                        },
                        new
                        {
                            Id = new Guid("81c9eadc-97a4-455f-a38e-276792e27d17"),
                            ArrivalDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sima15",
                            ShelterId = 1,
                            SpeciesId = 15,
                            Weight = 66.0
                        },
                        new
                        {
                            Id = new Guid("dfe739a0-7876-490b-9ab7-9a480eb88600"),
                            ArrivalDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cica15",
                            ShelterId = 1,
                            SpeciesId = 15,
                            Weight = 77.0
                        });
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Krnjaca"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Batajnica"
                        });
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kapucin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zlatni lavlji tamari"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mandril"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Babun"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Langur"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pauk majmun"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Veveričasti majmun"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rezus makaki"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gibon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Uakari"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Nosati majmun"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Džepni marmoset"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Howler majmun"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gvenon"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Dril"
                        });
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.VetCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MonkeyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MonkeyId");

                    b.ToTable("VetChecks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Monkey", b =>
                {
                    b.HasOne("MonkeyShelter.Core.Entities.Shelter", "Shelter")
                        .WithMany("Monkeys")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonkeyShelter.Core.Entities.Species", "Species")
                        .WithMany("Monkeys")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.VetCheck", b =>
                {
                    b.HasOne("MonkeyShelter.Core.Entities.Monkey", "Monkey")
                        .WithMany("VetChecks")
                        .HasForeignKey("MonkeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monkey");
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Monkey", b =>
                {
                    b.Navigation("VetChecks");
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Shelter", b =>
                {
                    b.Navigation("Monkeys");
                });

            modelBuilder.Entity("MonkeyShelter.Core.Entities.Species", b =>
                {
                    b.Navigation("Monkeys");
                });
#pragma warning restore 612, 618
        }
    }
}
